const express = require('express')
const passport = require('passport')
const router = express.Router()
const adminController = require('../../controllers/admin-controller')
const upload = require('../../middleware/multer')

router.get('/drinks/:id/edit', adminController.editDrinkPage)
router.delete('/drinks/:id/delete', adminController.deleteDrink)
router.put('/stores/:id/edit', adminController.putStore)
router.delete('/stores/:id/delete', adminController.deleteStore)
router.post('/drinks/search', adminController.searchDrink)
router.get('/drinks/:id', adminController.getDrink)
router.put('/drinks/:id', upload.single('image'), adminController.putDrink)
router.get('/login', adminController.loginPage)
// router.post('/login', passport.authenticate('local', { failureRedirect: '/admin/login', failureFlash: true }), adminController.login)
router.post('/login', passport.authenticate('local', { failureRedirect: '/admin/login' }), adminController.login)
router.post('/logout', adminController.logout)
router.post('/drinks', upload.single('image'), adminController.postDrink)
router.post('/stores', adminController.postStore)
router.get('/drinks', adminController.getDrinks)
router.get('/stores', adminController.getStoresPage)
router.get('/users', adminController.getUsersPage)
router.post('/users', adminController.postUser)

module.exports = router