const express = require('express')
const passport = require('passport')
const router = express.Router()
const adminController = require('../../controllers/admin-controller')
const upload = require('../../middleware/multer')
const authenticated = require('../../middleware/auth')

router.get('/drinks/:id/edit', authenticated, adminController.editDrinkPage)
router.delete('/drinks/:id/delete', authenticated, adminController.deleteDrink)
router.put('/stores/:id/edit', authenticated, adminController.putStore)
router.delete('/stores/:id/delete', authenticated, adminController.deleteStore)
router.put('/users/:id/edit', authenticated, adminController.putUser)
router.delete('/users/:id/delete', authenticated, adminController.deleteUser)
router.post('/drinks/search', authenticated, adminController.searchDrink)
router.get('/drinks/:id', authenticated, adminController.getDrink)
router.put('/drinks/:id', authenticated, upload.single('image'), adminController.putDrink)
router.get('/login', adminController.loginPage)
// router.post('/login', passport.authenticate('local', { failureRedirect: '/admin/login', failureFlash: true }), adminController.login)
router.post('/login', passport.authenticate('local', { failureRedirect: '/admin/login' }), adminController.login)
router.post('/logout', adminController.logout)
router.post('/drinks', authenticated, upload.single('image'), adminController.postDrink)
router.post('/stores', authenticated, adminController.postStore)
router.get('/drinks', authenticated, adminController.getDrinks)
router.get('/stores', authenticated, adminController.getStoresPage)
router.get('/users', authenticated, adminController.getUsersPage)
router.post('/users', authenticated, adminController.postUser)

router.get('/', (req, res) => res.redirect('/admin/drinks'))

module.exports = router